
-- 현재 숫자 획득
SELECT BOARD_SEQ.CURRVAL
FROM DUAL;

-- 다음 숫자 획득
SELECT BOARD_SEQ.NEXTVAL
FROM DUAL;

INSERT INTO MEMBER(MEM_ID, MEM_NAME, MEM_PW) 
VALUES('A', 'A', '1234');

ROLLBACK;

COMMIT;

INSERT INTO BOARD(BOARD_TXTNUM, MEM_ID ,BOARD_TIT, BOARD_CTN)
VALUES(BOARD_SEQ.NEXTVAL, 'A', '이게 성공하면', '쉽시다');

SELECT B.BOARD_TXTNUM, B.MEM_ID, B.BOARD_TIT, B.BOARD_CTN, 
       B.BOARD_REGIDATE, B.BOARD_HITS
FROM BOARD B INNER JOIN MEMBER M
                     ON B.MEM_ID = M.MEM_ID;
